<template>
    <div>
      <p>És veritat. Estic a la porta del teu cor, de dia i de nit. Tot i que no estiguis escoltant, tot i que dubtis que pugui ser jo, aquí estic: esperant la més petita senyal de resposta, fins al més petit suggeriment d'invitació que em permeti entrar.</p>
      <p>I vull que sàpigues que cada vegada que em convides, jo vinc sempre, sens falta. Vinc en silenci i invisible, però amb un poder i un amor infinits, portant els molts dons del meu Esperit. Vinc amb la meva misericòrdia, amb el meu desig de perdonar i de guarir-te, amb un amor cap a tu que va més enllà de la teva comprensió. Un amor a cada detall, tan gran com l'amor que he rebut del meu Pare «Jo us he estimat com el Pare m'estima a mi ...» (Jn. 15,10). Vinc desitjant consolar i donar-te força, aixecar-te i embenar totes les teves ferides. Et porto la meva llum, per dissipar la teva foscor i tots els teus dubtes. Vinc amb el meu poder, que em permet carregar-te a tu: amb la meva gràcia, per tocar el teu cor i transformar la teva vida. Vinc amb la meva pau, per tranquil·litzar la teva ànima.</p>
      <p>Et conec com el palmell de la mà, sé tot sobre tu, fins als cabells del teu cap he comptat. No hi ha res en la teva vida que no tingui importància per a mi. T'he seguit a través dels anys i sempre t'he estimat, fins en les teves pèrdues. Conec cadascun dels teus problemes. Conec les teves necessitats i les teves preocupacions i, sí, conec tots els teus pecats. Però et dic de nou que t'estimo, no pel que has fet o deixat de fer, t'estimo per tu, per la bellesa i la dignitat que el meu Pare et va donar al crear-te a la seva pròpia imatge. És una dignitat que moltes vegades has oblidat, una bellesa que has entelat pel pecat. Però t'estimo com ets i he vessat la meva sang per rescatar-te. Si només m'ho demanes amb fe, la meva gràcia tocarà tot el que necessita ser canviat en la teva vida: jo et donaré la força per alliberar-te del pecat i de tot el seu poder destructor.</p>
      <p>Sé el que hi ha en el teu cor, conec la teva solitud i totes les teves ferides, els rebutjos, els judicis, les humiliacions, Jo ho suportat tot abans que tu. I tot ho vaig suportar per tu, perquè poguessis compartir la meva força i la meva victòria. Conec, sobretot, la teva necessitat d'amor, sé què tan assedegat estàs d'amor i de tendresa. Però quantes vegades has desitjat satisfer la set en va, buscant aquest amor amb egoisme, tractant d'omplir el buit dins teu amb plaers passatgers, amb el buit encara més gran del pecat. Tens set d'amor? «Veniu a mi tots els que tinguin set ...» (Jn. 7, 37). Jo et saciaré i t'ompliré. Tens set de ser estimat? T'estimo més del que et pots imaginar ... fins al punt de morir a la creu per tu.</p>
      <p>Tinc set de tu. Sí, aquesta és l'única manera en què tot just puc començar a descriure el meu amor. Tinc set de tu. Tinc set d'estimar-te i que tu m'estimis. Tan preciós ets per a mi que tinc set de tu. Vine a mi i ompliré el teu cor i guariré les teves ferides. Et faré una nova creació i et donaré la pau encara en les teves proves. Tinc set de tu. Mai has de dubtar de la meva misericòrdia, del meu desig de perdonar, del meu anhel per beneir i viure la meva vida en tu, i que et accepto sense importar el que hagis fet. Tinc set de tu. Si et sents de poc valor als ulls del món, no importa. No hi ha ningú que m'interessi més en tot el món que tu. Tinc set de tu. Obre't a mi, vine a mi, tingues set de mi, dóna'm la teva vida. Jo et provaré què tan valuós ets per al meu Cor.</p>
      <p>No t'adones que el meu Pare ja té un pla perfecte per transformar la teva vida a partir d'aquest moment? Confia en mi. Demana-m'ho cada dia que entri i que em s'encarregui de la teva vida i ho faré. Et prometo davant el meu Pare en el Cel que faré miracles en la teva vida. Per què faria jo això? Perquè tinc set de tu. L'únic que et demano és que et confiïs completament en mi. Jo faré tota la resta.</p>
      <p>Des d'ara, ja veig el lloc que el meu Pare t'ha preparat en el meu Regne. Recorda que ets pelegrí en aquesta vida viatjant a casa. El pecat mai et pot satisfer ni portar-te la pau que anheles. Tot el que has buscat fora de mi només t'ha deixat més buit, així que no et lliguis a les coses d'aquest món; però, sobretot, no t'allunyis de mi quan caiguis. Vine a mi sense tardança perquè quan em dones els teus pecats, em dones l'alegria de ser el teu Salvador. No hi ha res que jo no pugui perdonar i curar, així que vine ara i descàrrega teva ànima.</p>
      <p>No importa quant hagis caminat sense rumb, no importa quantes vegades m'hagis oblidat, no importa quantes creus portis en aquesta vida. Hi ha alguna cosa que vull que sempre recordis i que mai canviarà. Tinc set de tu, tal com ets. No has de canviar per creure en el meu amor, ja que serà la teva confiança en aquest amor la que et farà canviar. Tu t'oblides de mi i, no obstant això, Jo et busco a cada moment del dia i estic davant les portes del teu cor, trucant. Trobes això difícil de creure? Llavors, mira la Creu, mira el meu Cor que va ser traspassat per tu. No has comprès la meva Creu ?, llavors escolta de nou les paraules que dic en ella, et diuen clarament per què jo vaig suportar tot això per tu: «... Tinc set de tu» (Jn. 19, 28). Sí, Tinc set de tu. Com la resta del salm que jo estava resant diu de mi: «... vaig esperar compassió inútilment, vaig esperar algú que em consolés i no el vaig trobar» (Salm 69, 20). Tota la teva vida he estat desitjant el teu amor. Mai he cessat de buscar-lo i de anhelar que em corresponguis. Tu has provat moltes coses en el teu afany per ser feliç. Per què no intentes obrir-me el cor, ara mateix, obrir-lo més del que ho has fet abans?</p>
      <p>Quan finalment obris les portes del teu cor i finalment t'acostis prou, llavors em sentiràs dir una i altra vegada, no en meres paraules humanes sinó en esperit: «No importa què és el que hagis fet, t'estimo per tu mateix. Vine a mi amb la teva misèria i els teus pecats, amb els teus problemes i necessitats, i amb tot el desig de ser estimat. Estic a la porta del teu cor i dic ... Obre'm, perquè TINC SET DE TU.</p>
    </div>
</template>

<script>
export default {
  // name: 'ComponentName',
  data () {
    return {}
  }
}
</script>

<style>
</style>
